/* This file is generated from assets/images and assets/icons. */
/* Run `node scripts/generate-local-icon-registry.js` after adding or removing local icon files. */

export const localIconRegistry = {
    "accident": { type: "image", source: require("../../assets/images/accident.png") },
    "atm": { type: "image", source: require("../../assets/images/atm.png") },
    "atm-detail": { type: "image", source: require("../../assets/images/atm-detail.png") },
    "atm-detail-page": { type: "image", source: require("../../assets/images/atm-detail-page.png") },
    "bad-weather": { type: "image", source: require("../../assets/images/bad-weather.png") },
    "bank": { type: "image", source: require("../../assets/images/bank.png") },
    "bank-detail": { type: "image", source: require("../../assets/images/bank-detail.png") },
    "bank-detail-page": { type: "image", source: require("../../assets/images/bank-detail-page.png") },
    "broken-road": { type: "image", source: require("../../assets/images/broken-road.png") },
    "building": { type: "image", source: require("../../assets/images/building.png") },
    "car-selected": { type: "image", source: require("../../assets/images/car-selected.png") },
    "car-unselected": { type: "image", source: require("../../assets/images/car-unselected.png") },
    "closure": { type: "image", source: require("../../assets/images/closure.png") },
    "coffee-shop": { type: "image", source: require("../../assets/images/coffee-shop.png") },
    "company": { type: "image", source: require("../../assets/images/company.png") },
    "crash": { type: "image", source: require("../../assets/images/crash.png") },
    "
    "curved-dark-light-2-user": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/2 User.svg") },
    "curved-dark-light-3-user": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/3 User.svg") },
    "curved-dark-light-activity": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Activity.svg") },
    "curved-dark-light-add-user": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Add User.svg") },
    "curved-dark-light-arrow-down": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Down.svg") },
    "curved-dark-light-arrow-down-2": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Down 2.svg") },
    "curved-dark-light-arrow-down-3": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Down 3.svg") },
    "curved-dark-light-arrow-down-circle": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Down Circle.svg") },
    "curved-dark-light-arrow-down-square": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Down Square.svg") },
    "curved-dark-light-arrow-left": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Left.svg") },
    "curved-dark-light-arrow-left-2": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Left 2.svg") },
    "curved-dark-light-arrow-left-3": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Left 3.svg") },
    "curved-dark-light-arrow-left-circle": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Left Circle.svg") },
    "curved-dark-light-arrow-left-square": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Left Square.svg") },
    "curved-dark-light-arrow-right": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Right.svg") },
    "curved-dark-light-arrow-right-2": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Right 2.svg") },
    "curved-dark-light-arrow-right-3": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Right 3.svg") },
    "curved-dark-light-arrow-right-circle": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Right Circle.svg") },
    "curved-dark-light-arrow-right-square": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Right Square.svg") },
    "curved-dark-light-arrow-up": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Up.svg") },
    "curved-dark-light-arrow-up-2": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Up 2.svg") },
    "curved-dark-light-arrow-up-3": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Up 3.svg") },
    "curved-dark-light-arrow-up-circle": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Up Circle.svg") },
    "curved-dark-light-arrow-up-square": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Arrow - Up Square.svg") },
    "curved-dark-light-bag": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Bag.svg") },
    "curved-dark-light-bag-2": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Bag 2.svg") },
    "curved-dark-light-bookmark": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Bookmark.svg") },
    "curved-dark-light-buy": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Buy.svg") },
    "curved-dark-light-calendar": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Calendar.svg") },
    "curved-dark-light-call": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Call.svg") },
    "curved-dark-light-call-missed": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Call Missed.svg") },
    "curved-dark-light-call-silent": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Call Silent.svg") },
    "curved-dark-light-calling": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Calling.svg") },
    "curved-dark-light-camera": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Camera.svg") },
    "curved-dark-light-category": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Category.svg") },
    "curved-dark-light-chart": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Chart.svg") },
    "curved-dark-light-chat": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Chat.svg") },
    "curved-dark-light-close-square": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Close Square.svg") },
    "curved-dark-light-danger-square": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Danger Square.svg") },
    "curved-dark-light-danger-triangle": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Danger Triangle.svg") },
    "curved-dark-light-delete": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Delete.svg") },
    "curved-dark-light-discount": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Discount.svg") },
    "curved-dark-light-discovery": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Discovery.svg") },
    "curved-dark-light-document": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Document.svg") },
    "curved-dark-light-download": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Download.svg") },
    "curved-dark-light-edit": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Edit.svg") },
    "curved-dark-light-edit-square": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Edit Square.svg") },
    "curved-dark-light-filter": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Filter.svg") },
    "curved-dark-light-filter-2": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Filter 2.svg") },
    "curved-dark-light-folder": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Folder.svg") },
    "curved-dark-light-game": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Game.svg") },
    "curved-dark-light-graph": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Graph.svg") },
    "curved-dark-light-heart": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Heart.svg") },
    "curved-dark-light-hide": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Hide.svg") },
    "curved-dark-light-home": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Home.svg") },
    "curved-dark-light-image": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Image.svg") },
    "curved-dark-light-image-2": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Image 2.svg") },
    "curved-dark-light-info-square": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Info Square.svg") },
    "curved-dark-light-location": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Location.svg") },
    "curved-dark-light-lock": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Lock.svg") },
    "curved-dark-light-login": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Login.svg") },
    "curved-dark-light-logout": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Logout.svg") },
    "curved-dark-light-message": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Message.svg") },
    "curved-dark-light-more-circle": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/More Circle.svg") },
    "curved-dark-light-more-square": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/More Square.svg") },
    "curved-dark-light-notification": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Notification.svg") },
    "curved-dark-light-paper": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Paper.svg") },
    "curved-dark-light-paper-download": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Paper Download.svg") },
    "curved-dark-light-paper-fail": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Paper Fail.svg") },
    "curved-dark-light-paper-negative": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Paper Negative.svg") },
    "curved-dark-light-paper-plus": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Paper Plus.svg") },
    "curved-dark-light-paper-upload": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Paper Upload.svg") },
    "curved-dark-light-password": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Password.svg") },
    "curved-dark-light-play": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Play.svg") },
    "curved-dark-light-plus": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Plus.svg") },
    "curved-dark-light-profile": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Profile.svg") },
    "curved-dark-light-scan": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Scan.svg") },
    "curved-dark-light-search": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Search.svg") },
    "curved-dark-light-send": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Send.svg") },
    "curved-dark-light-setting": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Setting.svg") },
    "curved-dark-light-shield-done": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Shield Done.svg") },
    "curved-dark-light-shield-fail": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Shield Fail.svg") },
    "curved-dark-light-show": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Show.svg") },
    "curved-dark-light-star": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Star.svg") },
    "curved-dark-light-swap": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Swap.svg") },
    "curved-dark-light-tick-square": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Tick Square.svg") },
    "curved-dark-light-ticket": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Ticket.svg") },
    "curved-dark-light-ticket-star": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Ticket Star.svg") },
    "curved-dark-light-time-circle": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Time Circle.svg") },
    "curved-dark-light-time-square": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Time Square.svg") },
    "curved-dark-light-unlock": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Unlock.svg") },
    "curved-dark-light-upload": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Upload.svg") },
    "curved-dark-light-video": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Video.svg") },
    "curved-dark-light-voice": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Voice.svg") },
    "curved-dark-light-voice-2": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Voice 2.svg") },
    "curved-dark-light-volume-down": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Volume Down.svg") },
    "curved-dark-light-volume-off": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Volume Off.svg") },
    "curved-dark-light-volume-up": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Volume Up.svg") },
    "curved-dark-light-wallet": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Wallet.svg") },
    "curved-dark-light-work": { type: "svg", source: require("../../assets/icons/curved/Dark/Light/Work.svg") },
    
    "curved-light-light-2-user": { type: "svg", source: require("../../assets/icons/curved/Light/Light/2 User.svg") },
    "curved-light-light-3-user": { type: "svg", source: require("../../assets/icons/curved/Light/Light/3 User.svg") },
    "curved-light-light-activity": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Activity.svg") },
    "curved-light-light-add-user": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Add User.svg") },
    "curved-light-light-arrow-down": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Down.svg") },
    "curved-light-light-arrow-down-2": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Down 2.svg") },
    "curved-light-light-arrow-down-3": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Down 3.svg") },
    "curved-light-light-arrow-down-circle": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Down Circle.svg") },
    "curved-light-light-arrow-down-square": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Down Square.svg") },
    "curved-light-light-arrow-left": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Left.svg") },
    "curved-light-light-arrow-left-2": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Left 2.svg") },
    "curved-light-light-arrow-left-3": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Left 3.svg") },
    "curved-light-light-arrow-left-circle": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Left Circle.svg") },
    "curved-light-light-arrow-left-square": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Left Square.svg") },
    "curved-light-light-arrow-right": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Right.svg") },
    "curved-light-light-arrow-right-2": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Right 2.svg") },
    "curved-light-light-arrow-right-3": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Right 3.svg") },
    "curved-light-light-arrow-right-circle": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Right Circle.svg") },
    "curved-light-light-arrow-right-square": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Right Square.svg") },
    "curved-light-light-arrow-up": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Up.svg") },
    "curved-light-light-arrow-up-2": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Up 2.svg") },
    "curved-light-light-arrow-up-3": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Up 3.svg") },
    "curved-light-light-arrow-up-circle": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Up Circle.svg") },
    "curved-light-light-arrow-up-square": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Arrow - Up Square.svg") },
    "curved-light-light-bag": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Bag.svg") },
    "curved-light-light-bag-2": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Bag 2.svg") },
    "curved-light-light-bookmark": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Bookmark.svg") },
    "curved-light-light-buy": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Buy.svg") },
    "curved-light-light-calendar": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Calendar.svg") },
    "curved-light-light-call": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Call.svg") },
    "curved-light-light-call-missed": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Call Missed.svg") },
    "curved-light-light-call-silent": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Call Silent.svg") },
    "curved-light-light-calling": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Calling.svg") },
    "curved-light-light-camera": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Camera.svg") },
    "curved-light-light-category": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Category.svg") },
    "curved-light-light-chart": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Chart.svg") },
    "curved-light-light-chat": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Chat.svg") },
    "curved-light-light-close-square": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Close Square.svg") },
    "curved-light-light-danger-square": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Danger Square.svg") },
    "curved-light-light-danger-triangle": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Danger Triangle.svg") },
    "curved-light-light-delete": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Delete.svg") },
    "curved-light-light-discount": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Discount.svg") },
    "curved-light-light-discovery": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Discovery.svg") },
    "curved-light-light-document": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Document.svg") },
    "curved-light-light-download": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Download.svg") },
    "curved-light-light-edit": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Edit.svg") },
    "curved-light-light-edit-square": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Edit Square.svg") },
    "curved-light-light-filter": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Filter.svg") },
    "curved-light-light-filter-2": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Filter 2.svg") },
    "curved-light-light-folder": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Folder.svg") },
    "curved-light-light-game": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Game.svg") },
    "curved-light-light-graph": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Graph.svg") },
    "curved-light-light-heart": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Heart.svg") },
    "curved-light-light-hide": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Hide.svg") },
    "curved-light-light-home": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Home.svg") },
    "curved-light-light-image": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Image.svg") },
    "curved-light-light-image-2": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Image 2.svg") },
    "curved-light-light-info-square": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Info Square.svg") },
    "curved-light-light-location": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Location.svg") },
    "curved-light-light-lock": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Lock.svg") },
    "curved-light-light-login": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Login.svg") },
    "curved-light-light-logout": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Logout.svg") },
    "curved-light-light-message": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Message.svg") },
    "curved-light-light-more-circle": { type: "svg", source: require("../../assets/icons/curved/Light/Light/More Circle.svg") },
    "curved-light-light-more-square": { type: "svg", source: require("../../assets/icons/curved/Light/Light/More Square.svg") },
    "curved-light-light-notification": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Notification.svg") },
    "curved-light-light-paper": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Paper.svg") },
    "curved-light-light-paper-download": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Paper Download.svg") },
    "curved-light-light-paper-fail": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Paper Fail.svg") },
    "curved-light-light-paper-negative": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Paper Negative.svg") },
    "curved-light-light-paper-plus": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Paper Plus.svg") },
    "curved-light-light-paper-upload": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Paper Upload.svg") },
    "curved-light-light-password": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Password.svg") },
    "curved-light-light-play": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Play.svg") },
    "curved-light-light-plus": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Plus.svg") },
    "curved-light-light-profile": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Profile.svg") },
    "curved-light-light-scan": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Scan.svg") },
    "curved-light-light-search": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Search.svg") },
    "curved-light-light-send": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Send.svg") },
    "curved-light-light-setting": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Setting.svg") },
    "curved-light-light-shield-done": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Shield Done.svg") },
    "curved-light-light-shield-fail": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Shield Fail.svg") },
    "curved-light-light-show": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Show.svg") },
    "curved-light-light-star": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Star.svg") },
    "curved-light-light-swap": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Swap.svg") },
    "curved-light-light-tick-square": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Tick Square.svg") },
    "curved-light-light-ticket": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Ticket.svg") },
    "curved-light-light-ticket-star": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Ticket Star.svg") },
    "curved-light-light-time-circle": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Time Circle.svg") },
    "curved-light-light-time-square": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Time Square.svg") },
    "curved-light-light-unlock": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Unlock.svg") },
    "curved-light-light-upload": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Upload.svg") },
    "curved-light-light-video": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Video.svg") },
    "curved-light-light-voice": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Voice.svg") },
    "curved-light-light-voice-2": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Voice 2.svg") },
    "curved-light-light-volume-down": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Volume Down.svg") },
    "curved-light-light-volume-off": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Volume Off.svg") },
    "curved-light-light-volume-up": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Volume Up.svg") },
    "curved-light-light-wallet": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Wallet.svg") },
    "curved-light-light-work": { type: "svg", source: require("../../assets/icons/curved/Light/Light/Work.svg") },

} as const;

export type LocalIconName = keyof typeof localIconRegistry;
export type LocalIconAsset = (typeof localIconRegistry)[LocalIconName];
